spring:
  application:
    name: microservice-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice1?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.chao.common.entity
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml