spring:
  application:
    name: shop-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_shop?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: true
server:
  port: 8101

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
info:
  app.name: 订单微服务
  app.version: @project.version@
